export {
  createHostel,
  createRoom,
  deleteHostel,
  fetchHostelBedDetails,
  fetchHostelBeds,
  patchHostelBed,
  fetchHostelDetails,
  fetchHostelRooms,
  fetchOwnerDashboardAnalytics,
  fetchOwnerRequestsInbox,
  fetchHostels,
  fetchMyHostels,
  publishHostel,
  respondToOwnerRequest,
  requestHostelRoom,
  trackHostelCallClick,
  updateHostel,
} from '../../application/hostels/hostelsService'
